// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHVrfsWzBB2oNg4RgqBlZSqt0scmU1pXM',
    appId: '1:870489630345:android:60c3c690a9b5d72c974858',
    messagingSenderId: '870489630345',
    projectId: 'smartechsdk-3xx',
    databaseURL: 'https://smartechsdk-3xx.firebaseio.com',
    storageBucket: 'smartechsdk-3xx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2uMN4KPM1I_1qIzS5YZKNzi-0wNicwbc',
    appId: '1:870489630345:ios:887f6d2dfc26abde974858',
    messagingSenderId: '870489630345',
    projectId: 'smartechsdk-3xx',
    databaseURL: 'https://smartechsdk-3xx.firebaseio.com',
    storageBucket: 'smartechsdk-3xx.appspot.com',
    iosClientId: '870489630345-qreefp41hdkgl0s2hll0s24f0kghvmgn.apps.googleusercontent.com',
    iosBundleId: 'com.netcore.SmartechApp',
  );
}
